services:
  - type: web
    name: tz-django
    runtime: docker
    plan: free
    healthCheckPath: /
    dockerCommand: bash start.sh
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: tz-django-db
          property: connectionString
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: "False"
      - key: DJANGO_ALLOWED_HOSTS
        value: ".onrender.com,localhost,127.0.0.1"
      - key: STRIPE_PUBLISHABLE_KEY_USD
        sync: false
      - key: STRIPE_SECRET_KEY_USD
        sync: false
      - key: STRIPE_PUBLISHABLE_KEY_RUB
        sync: false
      - key: STRIPE_SECRET_KEY_RUB
        sync: false

databases:
  - name: tz-django-db
    plan: free
